name: Sync Branch with Master

on:
  schedule:
    - cron: '0 0 * * *' # every hour
  workflow_dispatch: # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout your branch
        run: git checkout Tomasz---Booking-Management

      - name: Merge master into your branch
        run: git merge origin/master

      - name: Push changes
        run: git push origin your-branch-name
